version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - mkdir temp
      - mkdir build
      - pip3.8 install -r app/requirements.txt -t temp
      - cp -a app/. temp/
      - cd temp
      - chmod -R 755 .
      - zip -r ../build/brownbag-$CODEBUILD_BUILD_NUMBER.zip .
artifacts:
  files:
    - brownbag-$CODEBUILD_BUILD_NUMBER.zip
  base-directory: build
  discard-paths: yes

#environment:
#  type: "LINUX_CONTAINER"
#  image: "aws/codebuild/standard:4.0"
