version: "3"


services:

  proxy:
    build:
      context: proxy
    ports:
      - 80:80

  ui:
    build:
      context: ui
    ports:
      - 8080:80
  api:
    build: 
      context: api
    ports:
      - 8888:80
    env_file:
    - ./secret/.env
  postgres:
    image: "postgres:11.8-alpine"
    ports:
      - "5432:5432"
    env_file:
      - ./secret/.env
    volumes:
      - type: bind
        source: /data/postgres/
        target: /var/lib/postgresql/data

#volumes:
#  # brownbag_data:




